a = [[["0", "1"], ["2", "3"], ["4", "5"]], [["6", "7"], ["8", "9"], ["10", "11"]], [["12", "13"], ["14", "15"], ["16", "17"]]]
b = [["0", "1", "1"], ["1", "0", "1"], ["1", "1", "0"]]
desired = [["0", "3", "5"], ["7", "8", "11"], ["13", "15", "16"]]
