input = [["0", "0", "0", "0", "0", "0"], ["0", "0", "5", "1", "2", "0"], ["0", "1", "8", "0", "1", "0"], ["0", "0", "0", "7", "1", "0"], ["0", "0", "0", "0", "0", "0"]]
result = [["0", "5", "1", "2"], ["1", "8", "0", "1"], ["0", "0", "7", "1"]]
