a = [["1", "5", "9", "13"], ["2", "6", "10", "14"], ["3", "7", "11", "15"], ["4", "8", "12", "16"]]
result = [[["1", "5"], ["2", "6"]], [["9", "13"], ["10", "14"]], [["3", "7"], ["4", "8"]], [["11", "15"], ["12", "16"]]]
