a = [
  [
    ["10", "20"],
    ["30", "40"],
  ],
  [
    ["6", "7"],
    ["8", "9"],
  ],
  [
    ["10", "11"],
    ["12", "13"],
  ],
]

permutation = ["1", "0", "2"]

result = [
  [
    ["6", "7"],
    ["8", "9"],
  ],
  [
    ["10", "20"],
    ["30", "40"],
  ],
  [
    ["10", "11"],
    ["12", "13"],
  ],
]
