from .op_all import NDArray_AllOp
from .op_any import NDArray_AnyOp
from .op_argmax import NDArray_ArgMaxOp
from .op_argmin import NDArray_ArgMinOp
from .op_dtype import NDArray_DtypeOp
from .op_flat import NDArray_FlatOp
from .op_max import NDArray_MaxOp
from .op_min import NDArray_MinOp
from .op_reshape import NDArray_ReshapeOp
from .op_shape import NDArray_ShapeOp
from .op_sum import NDArray_SumOp
from .op_prod import NDArray_ProdOp
from .op_T import NDArray_TOp
from .op_transpose import NDArray_TransposeOp
from .op_tolist import NDArray_ToListOp
from .op_astype import NDArray_AsTypeOp
from .op_ndim import NDArray_NdimOp
from .op_repeat import NDArray_RepeatOp
from .op_size import NDArray_SizeOp
from .op_flatten import NDArray_FlattenOp