from .clazz import ClassValue
from .floating import FloatValue
from .integer import IntegerValue
from .lst import ListValue
from .ndarray import NDArrayValue
from .none import NoneValue
from .number import NumberValue
from .string import StringValue
from .tupl import TupleValue
from .value import Value