a = [
  ["1", "0", "3"],
  ["2", "4", "1"],
]

result = [
  ["0", "1", "0", "0", "0"],
  ["1", "0", "0", "0", "0"],
  ["0", "0", "0", "1", "0"],
  ["0", "0", "1", "0", "0"],
  ["0", "0", "0", "0", "1"],
  ["0", "1", "0", "0", "0"],
]
